spring:
  application:
    name: gateway-company
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 存栏微服务路径配置,其他微服务配置类似
        - id: pig-service-inventory
          uri: http://localhost:18081/
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1

server:
  port: 8001
#eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
